title: MysticSnatch
description: A game in Kotlin, libKTX and libGDX
theme: just-the-docs
remote_theme: "pmarsceill/just-the-docs"

url: https://bijumon.github.io/MysticSnatch/

aux_links:
  Source at github: https://github.com/bijumon/MysticSnatch

plugins:
  - jekyll-default-layout